Lesson4
vytcus/avalionis pull request #5
Opened 2021-05-19 12:20 UTC by AmadejusV

2021-05-19 12:36 UTC, vytcus requested changes

2021-05-19 12:36 UTC, vytcus commented on eshop/src/product/product.jsx
> +import React from "react";
Dėčiau šitą komponentą į products/components/Product.jsx (nepamirštam - PascalCase komponentų failų pavadinimams). Nes būtent Products komponente mes jį naudojam

2021-05-19 14:11 UTC, AmadejusV commented on eshop/src/product/product.jsx
> +import React from "react";
Sukeliau Product ir ProductPage i products/components

2021-05-19 14:14 UTC, vytcus requested changes

2021-05-19 14:14 UTC, vytcus commented on eshop/src/products/components/product-page/ProductPage.jsx
> +import React from "react";
ProductPage nereikėjo iškelti - jis yra kaip atskiras feature. T.y, Products komponentas jo nenaudoja.

2021-05-19 15:57 UTC, AmadejusV commented on eshop/src/products/components/product-page/ProductPage.jsx
> +import React from "react";
Aciu, sutaisiau :}

2021-05-20 07:45 UTC, vytcus approved these changes

2021-05-20 13:43 UTC, merged