Lesson7
vytcus/avalionis pull request #8
Opened 2021-06-10 17:45 UTC by AmadejusV

2021-06-11 06:10 UTC, vytcus requested changes

2021-06-11 06:10 UTC, vytcus commented on eshop/src/common/components/Spinner.jsx
> +  const [dots, setDots] = useState("");
Tau nereikia dviejų state'ų šitam dalykui. Iš esmės gali pasilikti dots arba dotCount.

2021-06-11 06:10 UTC, vytcus commented on eshop/src/common/components/Spinner.jsx
> +    // console.log("sat interval");
trinam

2021-06-11 06:10 UTC, vytcus commented on eshop/src/common/components/Spinner.jsx
> +    }
Dot'ų keitimą galima aprašyti viena eilute. Galvok iš ternary expression pusės.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator
Jei dotai trys -> nusetinam į vieną(arba nulį), jei ne -> pridedam vieną prie esančių dotų

2021-06-11 06:10 UTC, vytcus commented on eshop/src/common/components/Spinner.jsx
> +  useEffect(() => {
Šito use effecto nereikės

2021-06-11 17:05 UTC, AmadejusV commented on eshop/src/common/components/Spinner.jsx
> +  useEffect(() => {
Aciu! Pataisiau, beje ar yra skirtumas ar funkcija naudojama apsirasau useEffect viduje ar uz jo scope ribu?

2021-06-12 11:24 UTC, vytcus approved these changes

2021-06-13 13:26 UTC, merged